name = "scaffold"
compatibility_date = "2024-09-12"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]

# [[d1_databases]]
# binding = "DB" # i.e. available in your Worker on env.DB
# database_name = "scaffold-db"
# database_id = "f467f639-2d73-4d04-9eaa-4c7cb303c8e7"

[vars]
# MY_VAR = "my-variable"
AUTH_SECRET="<REPLACE_ME>"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"